USE SCHEMA BOM;
CREATE
	OR replace VIEW BMATHUB_XFRM.V_ITEM_DETAIL_ROOT (
	ITEM_ID
	,ITEM_CLASS_NM
	,ITEM_DSC
	,DELETE_IND
	) AS

SELECT ITEM_ID
	,ITEM_CLASS_NM
	,ITEM_DSC
	,DELETE_IND
FROM BMATHUB_BASE.T_ITEM_DETAIL_ROOT