USE SCHEMA BOM;
CREATE
	OR replace VIEW BMATHUB_XFRM.V_ORIG_BOM_ROOT (
	ITEM_ID
	,ITEM_CLASS_NM
	,OUTPUT_ITEM_ID
	,LOCATION
	) AS

SELECT ITEM_ID
	,ITEM_CLASS_NM
	,OUTPUT_ITEM_ID
	,LOCATION
FROM BMATHUB_BASE.T_ORIG_BOM_ROOT;