USE SCHEMA BOM;
CREATE
	OR replace VIEW BMATHUB_XFRM.V_COMPRESS_BOM_CORE (
	ITEM
	,ITEM_CLASS_NM
	,ANCHOR_ITEM_ID
	,BOM_NUM
	,LOC
	,CREATE_DTM
	,CREATE_USER
	) AS

SELECT ITEM
	,ITEM_CLASS_NM
	,ANCHOR_ITEM_ID
	,BOM_NUM
	,LOC
	,CREATE_DTM
	,CREATE_USER
FROM BMATHUB_BASE.T_COMPRESS_BOM_CORE;