CREATE
	OR replace VIEW BMATHUB_ANALYSIS.V_SIM_BOM (
	ITEM
	,ANCHOR_ITEM_ID
	,BOM_NUM
	,LOC
	,DESCRIE
	) AS

SELECT vbom.ITEM
	,vbom.ANCHOR_ITEM_ID
	,vbom.BOM_NUM
	,vbom.LOC
	,i.ITEM_DSC
FROM BMATHUB_XFRM.V_COMPRESS_BOM_CORE vbom
INNER JOIN BMATHUB_BASE.T_ITEM_DETAIL_ROOT i ON vbom.ITEM = i.ITEM_ID