USE SCHEMA BOM;
CREATE
	OR replace VIEW BMATHUB_ANALYSIS.V_SIM_BOM (
	ITEM
	,ANCHOR_ITEM_ID
	,BOM_NUM
	,LOC
	,DESCRIE
	) AS

SELECT C.ITEM
	,C.ANCHOR_ITEM_ID
	,C.BOM_NUM
	,C.LOC
	,I.ITEM_DSC
FROM BMATHUB_XFRM.V_COMPRESS_BOM_CORE C
INNER JOIN BMATHUB_XFRM.V_ITEM_DETAIL_ROOT I ON C.ITEM_CLASS_NM = I.ITEM_CLASS_NM;