USE SCHEMA BOM;
CREATE
	OR replace TABLE BMATHUB_BASE.T_COMPRESS_BOM_CORE (
	ITEM VARCHAR(21)
	,ITEM_CLASS_NM VARCHAR(30)
	,ANCHOR_ITEM_ID VARCHAR(21)
	,BOM_NUM INTEGER
	,LOC VARCHAR(10)
	,CREATE_DTM DATE
	,CREATE_USER VARCHAR(20)
	)