USE ORDER_PROCESS.ORDER_ANALYSIS;

create or replace view order_process.order_analysis.V_BY_INVOICE(
ORDER_ID,
ORDER_DATE,
INVOICE_DATE,
TOTAL_AMOUNT,
DISCOUNT,
TAX_AMOUNT,
FINAL_INVOICE_AMT,
CUSTOMER_ID,
CREATE_DATE,
CREATE_USER
) AS SELECT * FROM ORDER_PROCESS.ORDER_XFRM.V_INVOICE