USE ORDER_PROCESS.ORDER_XFRM;

CREATE OR REPLACE VIEW ORDER_PROCESS.ORDER_XFRM.V_ORDER_HEADER (
ORDER_ID,
ORDER_DATE,
STATUS,
CUSTOMER_ID,
ITEM_COUNT,
TOTAL_AMOUNT,
DISCOUNT,
CREATE_DATE,
CREATE_USER,
COUPON_CODE
) AS 
SELECT ORDER_ID,
ORDER_DATE,
STATUS,
CUSTOMER_ID,
ITEM_COUNT,
TOTAL_AMOUNT,
DISCOUNT,
CREATE_DATE,
CREATE_USER,
COUPON_CODE FROM ORDER_PROCESS.ORDER_BASE.T_ORDER_HEADER;