USE ORDER_PROCESS.ORDER_XFRM;

CREATE OR REPLACE VIEW ORDER_PROCESS.ORDER_XFRM.V_CUSTOMER(
CUSTOMER_ID,
ADDRESS,
PHONE_NO,
CATEGORY,
STATUS,
TOTAL_ORDERS,
TOTAL_INVOICE_AMOUNT,
LOYALTY_POINTS,
CREATE_DATE,
CREATE_USER
) AS SELECT
c.CUSTOMER_ID,
c.ADDRESS,
c.PHONE_NO,
c.CATEGORY,
c.STATUS,
c.TOTAL_ORDERS,
i.FINAL_INVOICE_AMT,
c.LOYALTY_POINTS,
c.CREATE_DATE,
c.CREATE_USER FROM ORDER_PROCESS.ORDER_BASE.T_CUSTOMER c inner join 
order_process.order_xfrm.v_invoice i on c.customer_id = i.customer_id