USE ORDER_PROCESS.ORDER_XFRM;

CREATE OR REPLACE VIEW ORDER_PROCESS.ORDER_XFRM.V_INVOICE(
ORDER_ID,
ORDER_DATE,
INVOICE_DATE,
TOTAL_AMOUNT,
DISCOUNT,
FINAL_INVOICE_AMT,
TAX_AMOUNT,
CUSTOMER_ID,
CREATE_DATE,
CREATE_USER
) AS SELECT
ORDER_ID,
ORDER_DATE,
INVOICE_DATE,
TOTAL_AMOUNT,
DISCOUNT,
FINAL_INVOICE_AMT,
TAX_AMOUNT,
CUSTOMER_ID,
CREATE_DATE,
CREATE_USER
FROM ORDER_PROCESS.ORDER_BASE.T_INVOICE;